@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor CLASS_ARROW_COLOR
skinparam classBackgroundColor CLASS_DIAGRAM_COLOR
skinparam classAttributeIconSize 0

Class ExerciseList {
    + exerciseList: ArrayList<Exercise>
    + exerciseListAll: ArrayList<Exercise>

    + ExerciseList()
    + handleListExercises(): void
    + handleListExercisesAll(): void
    + handleCaloriesBurnt(): void
    + handleListExercisesDate(command: String): void
    + handleDeleteExercisesDate(command: String): void
    + handleExercises (command: String): void
    + handleAddNewExerciseCalories(command: String): void
    + printExerciseList(exerciseListToPrint: ArrayList<Exercise>): void
}

Class Exercise {
    + <u>exerciseDetails: HashMap<String, int[]>
    - name: String
    - duration: int
    - intensity: ExerciseIntensity
    - caloriesBurnt: int
    - dateAdded: String

    + Exercise(name: String, duration: int, intensity: ExerciseIntensity, currentDate: String)
    + getName(): String
    + getDuration(): int
    + getIntensity(): ExerciseIntensity
    + getDate(): String
    + getCaloriesBurnt(): long
    + <u>handleInfoExercise(command: String): void
    + <u>printAvailableExercises(): void
    + <u>listAvailableExercises(): void
    + <u>getExerciseDetails(): HashMap<String, int[]>
    - setCaloriesBurnt(): void
    - isValidIntensity(intensity: ExerciseIntensity): boolean
}

Class "<<enumeration>>\nExerciseIntensity" as ExerciseIntensity {
    HIGH
    MEDIUM
    LOW
}

ExerciseList -down-> "*" Exercise

Exercise "*" *-down-> "1" ExerciseIntensity
@enduml